USE TEST;
--Join (It shows only matches)
SELECT P.BOID, P.NAME, P.LASTNAME, E.JOBTITLE, E.HIREDATE, E.SALARY
FROM DB.PEOPLE P 
INNER JOIN DB.EMPLOYEES AS E
ON E.BOID = P.BOID;

--Left Join (Full people, including not employees. NULL for not employees)
SELECT P.BOID, P.NAME, P.LASTNAME, E.JOBTITLE, E.HIREDATE, E.SALARY
FROM DB.PEOPLE P 
LEFT JOIN DB.EMPLOYEES AS E
ON E.BOID = P.BOID;

--Join does not includes nulls
SELECT C.boid, E.JOBTITLE, E.HIREDATE, E.SALARY, E.LOCATION
FROM DB.CLIENTS C
INNER JOIN DB.EMPLOYEES AS E
ON C.income = E.salary;

-- Including null handling (low performance)
SELECT C.boid, E.JOBTITLE, E.HIREDATE, E.SALARY, E.LOCATION
FROM DB.CLIENTS C
INNER JOIN DB.EMPLOYEES AS E
ON ISNULL(C.income, 0) = ISNULL(E.salary, 0);

--(high performance)
SELECT C.boid, E.JOBTITLE, E.HIREDATE, E.SALARY, E.LOCATION
FROM DB.CLIENTS C
INNER JOIN DB.EMPLOYEES AS E
ON C.income = E.salary
OR (C.income IS NULL AND E.salary IS NULL);

--Multi Join
SELECT P.*, C.income, T.contact, T.contacttype 
FROM DB.PEOPLE P 
JOIN DB.CLIENTS C
ON P.boid = C.BOID
JOIN DB.CONTACT T
ON P.boid = T.boid
WHERE T.contacttype = 'A';